Revert "update gzip requests"
This reverts commit 401d3521f6f2537ce58d0135c94fd6937d3f77b7.

root@vuduo2:~# python
Python 2.7.3 (default, Sep  7 2013, 12:14:16)
[GCC 4.8.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gzip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gzip