info.py: Don't assume that fileExists implies that the file can be read
Fix crashes like this:

/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/info.py:93 in getLinkSpeed
92 f = open('/sys/class/net/' + iface + '/speed','r')
93 speed = f.read().strip()
94 f.close()
exceptions.IOError: [Errno 22] Invalid argument

Instead of fileExists, just try to open and read the file, and handle
exceptions. That is correct, race-free and even faster.