Bugfix - WOL TypeError
This change also tidies response bodies and capitalises response headers.

File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/wol.py", line 134, in render
	    my_socket.sendto(magic, (ip, port))
	builtins.TypeError: a bytes-like object is required, not 'str'