base.py: getRcFolder might missing although boxbranding exists
OpenPLi doesn't contain getRcForlder (http://sourceforge.net/p/openpli/enigma2/ci/master/tree/lib/python/Components/RcModel.py)

  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
  File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 151, in render
    args = self.prepareMainTemplate()
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py", line 200, in prepareMainTemplate
    ret["remote"] = rc_model.getRcFolder()+remotesuffix
exceptions.AttributeError: RcModel instance has no attribute 'getRcFolder'

Call getRcFolder inside try and use as failback the OWIF getRcFolder...